language: cpp
compiler: gcc

before_install:
  - sudo apt-get update -qq
install:
  - sudo apt-get install -qq cppcheck

script:
  - pushd Source/Physics/tests
  - bash test.sh
  - popd
#  - pushd Source/Physics
#  - cppcheck --suppress='*:tests/*' --error-exitcode=1 .
#  - popd

branches:
  only:
  - master

git:
  lfs_skip_smudge: true
