language: cpp
compiler: gcc

before_install:
  - sudo apt-get update -qq
install:
  - sudo apt-get install -qq cppcheck

script:
  - cd Source/Physics && ./test.sh
  - cppcheck --error-exitcode=1 .

branches:
  only:
  - master

git:
  lfs_skip_smudge: true
